### PR TITLE
Update troubleshooting instructions

### PR DESCRIPTION
**Pull request by DenisGorbachev**

### CODE REVIEW

**Comment by hiroshi** [comment]
Thanks for your contribution.

However, disabling the open browser functionality may cause some troubles (see https://github.com/gyazo/Gyazo-for-Linux/pull/109).

So we should add some notes for this section.
```
NOTE: Disabling the open browser functionality may cause some troubles (see https://github.com/gyazo/Gyazo-for-Linux/pull/109).
```

We'll add this line before/after merging this pull request.

**Comment by pastak** [comment]
@DenisGorbachev Would you tell us why you add this troubleshooting instructions. 

I'm not agree to write it on README because this confuses user. I have no idea that this instruction works.

**Comment by hiroshi** [comment]
I can understand some people don't want to open images in a browser tab/window just after uploading.
Official Windows version of Gyazo client has this option in preferences for those.

Yep, but it should not be in the troubleshooting section of README I think. New sections like Tips or HowTo can be more suitable, or somewhere else I'm not sure.

**Comment by rewdel** [comment]
I'm unable to find the .gyazo.config.yml file from  `$HOME/.gyazo.config.yml` to add the:

```yaml
browser_cmd: echo
```

code to prevent the web browser pop up. Any suggestions?

**Pull request closed without merging**
