### PR TITLE
Feature/get active window name

### PR DESCRIPTION
**Pull request by pastak**
- Download deb package: https://drive.google.com/file/d/0B7grzLMEgNxzWWZsNjZhZHFoY2c/view?usp=sharing
- require `$sudo apt-get install ruby imagemagick xdotool`
- Install `$sudo dpkg -i gyazo_XXX_all.deb`

### CODE REVIEW

**Comment by rakusai** [comment]
let's merge this after gyazo.com server supported to accept this parameter.

**Comment by pastak** [comment]
:+1:

**Comment by drobune** [comment]
:rocket:

**Comment by drobune** [comment]
マージしてしまいたい...

**Comment by drobune** [comment]
merged at #31

**Pull request closed without merging**
