### PR TITLE
Adding translation to the Desktop file

### PR DESCRIPTION
**Pull request by branchard**
I just added a French and Spanish translation in the Desktop file.

### CODE REVIEW

**Comment by pastak** [comment]
@branchard Thanks for your great works!

We make enable CI to forked PR ( was disabled by CIrcleCI ).

So please you do `git commit --amend --no-edit . && git push -f origin master`

**Comment by branchard** [comment]
Is it good now?

**Comment by pastak** [comment]
looks good

**Comment by Lorybat1998UCD** [comment]
I added italian about a week ago or so.

**Pull request merged**
